baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[menu]
    [[menu.items]]
        name = 'Home'
        url = '/'
        weight = 10
    [[menu.items]]
        name = 'Info'
        url = '/info'
        weight = 20
    [[menu.items]]
        name = 'Posts'
        url = '/posts'
        weight = 30

[taxonomies]
    author = 'author'

